GET http://localhost:3000/api/groups

###

POST http://localhost:3000/api/groups
Content-Type: application/json

{
  "name": "테스트용 그룹",
  "description": "테스트 테스트",
  "isPublic": true,
  "password": "securepassword123"
}

###
PUT http://localhost:3000/api/groups/f9465783-79c3-4427-8543-ddf9630ba664
Content-Type: application/json

{
  "name": "테스트 수정",
  "description": "테스트 테스트",
  "isPublic": true,
  "password": "securepassword123"
}

###
DELETE http://localhost:3000/api/groups/1
